# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-18 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatable', '0002_enroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqnum', models.CharField(max_length=30)),
                ('stu_num', models.CharField(max_length=30)),
                ('stu_name', models.CharField(max_length=30)),
            ],
        ),
    ]
